# Generated by Django 5.1.6 on 2025-02-27 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institute', '0003_instituterequest_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('action_date', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute.instituterequest')),
            ],
        ),
    ]
