# Generated by Django 5.1.6 on 2025-02-27 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admapp', '0001_initial'),
        ('institute', '0003_instituterequest_approved_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequestQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('institute_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_queue', to='institute.instituterequest')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminAction',
        ),
    ]
