# Generated by Django 5.1.6 on 2025-02-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_rename_donor_donorperson_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Unique transaction ID from payment gateway', max_length=100, null=True),
        ),
    ]
