# Generated by Django 5.1.6 on 2025-02-27 20:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Store',
        ),
        migrations.RenameField(
            model_name='shoporder',
            old_name='shop',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='shoprating',
            old_name='shop',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='shop',
            new_name='store',
        ),
    ]
