# Generated by Django 5.1.6 on 2025-02-28 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0005_alter_institutedocument_document'),
        ('shop', '0002_rename_shop_store_rename_shop_shoporder_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='institute.instituterequest')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='shop.store')),
            ],
        ),
    ]
