# Generated by Django 5.1.6 on 2025-02-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopprofile',
            name='shop_name',
            field=models.CharField(max_length=255),
        ),
    ]
