# Generated by Django 5.1.6 on 2025-02-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_institutedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutedocument',
            name='document',
            field=models.FileField(blank=True, default='default.jpg', null=True, upload_to='institute_documents/'),
        ),
    ]
